name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: django_db
        options: >-
          --health-cmd "pg_isready -U postgres -d django_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_NAME: django_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost  
      DATABASE_PORT: 5432

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Wait for Postgres
        run: until pg_isready -h localhost -p 5432 -U postgres; do sleep 1; done

      - name: Run migrations (expected to fail for now)
        env:
          DATABASE_NAME: django_db
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
        run: |
          python blog_project/manage.py migrate

      - name: Run tests (expected to fail for now)
        env:
          DATABASE_NAME: django_db
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
        run: |
          python blog_project/manage.py test
